name: Run TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run TestNG tests
        run: mvn test -DsuiteXmlFile=src/test/java/suite/allTests.xml

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        with:
           name: cucumberReport
           path: cucumberReport.html